*
*         Name: CMSFSCAT 8 ("man page" nroff source)
*       Author: Rick Troth, BMC Software, Inc., Houston, Texas, USA
*         Date: 2000-Sep-10 (Sun)
*
 
.TH CMSFSCAT 8 "Fri, 2000 Sep 08" CMSFS "CMSFS version 1.0"
.UC 4
.SH NAME
cmsfscat \- extract files from CMS formatted volumes.
.SH SYNOPSIS
\fBcmsfscat\fR [-d \fIcmsvol\fR] [-a | -i] \fIcmsfile\fR
.SH DESCRIPTION
\fBcmsfscat\fR
reads files from CMS volumes for usage on Linux/390.
\fBcmsfscat\fR writes to stdout.
 
.SH OPTIONS
.TP
\fB-d\fR \fIcmsvol\fR
Specify the device to be used.
\fIcmsvol\fR can be a regular file.
 
.TP
\fB-a\fR
Extract files as plain text (ASCII).
 
.TP
\fB-i\fR
Extract files as binary (IMAGE).
 
.TP
\fIcmsfile\fR
Specify the file to read from CMS.
 
.SH BUGS
none (that we have yet found)
 
.SH AUTHOR
.nf
This man-page written by Rick Troth <rtroth@bmc.com>,
modelled after one written by Fritz Elfert <felfert@to.com>.
.fi
 
.SH SEE ALSO
.BR cmsfsvol (8)
.BR cmsfslst (8)
.BR cmsfsck (8)
.BR cmsfscp (8)
.BR readcms (8)
.BR cmsmount (8)
 
