*
*         Name: CMSFSLST 8 ("man page" nroff source)
*       Author: Rick Troth, BMC Software, Inc., Houston, Texas, USA
*         Date: 2000-Sep-10 (Sun)
*
 
.TH CMSFSLST 8 "Sun, 2000 Sep 10" CMSFS "CMSFS version 1.0"
.UC 4
 
.SH NAME
cmsfslst \- list files on CMS formatted volumes
in CMS 'LISTFILE' style output.
 
.SH SYNOPSIS
\fBcmsfslst\fR [-d \fIcmsvol\fR]
 
.SH DESCRIPTION
\fBcmsfslst\fR
reads directory information from CMS volumes
and reports in the same format as the CMS 'LISTFILE'.
Output is comparable to the effect of the \fB(FULLDATE\fR option.
 
.SH OPTIONS
.TP
\fB-d\fR \fIcmsvol\fR
Specify the device to be used.
\fIcmsvol\fR can be a regular file.
 
.SH BUGS
none (that we have yet found)
 
.TP
The \fI.DIRECTOR\fR and \fI.ALLOCMAP\fR files are
intentionally not omitted from the listing.
 
.SH AUTHOR
.nf
This man-page and utility written by Rick Troth <rtroth@bmc.com>.
.fi
 
.SH SEE ALSO
.BR cmsfscat (8)
.BR cmsfsvol (8)
.BR cmsfscp (8)
.BR cmsfsck (8)
.BR readcms (8)
.BR cmsmount (8)
 
